substitutions:
  device_name: <device name>
  ip_addr: <ip>

esphome:
  name: ${device_name}

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome 
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid_cali
  password: !secret wifi_password_cali
  use_address: ${ip_addr}
  domain: !secret domain_cali
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password_cali

captive_portal:

status_led:
  pin:
    number: 2
    inverted: true

# Example configuration entry
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_warm_white
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_cold_white
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_work_area

light:
  - platform: cwww
    name: "Desk Lamp"
    cold_white: pwm_cold_white
    warm_white: pwm_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true
  - platform: monochromatic
    name: "Work Area Light"
    output: pwm_work_area

